name: ROS
on:
  push:
    paths-ignore:
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - '*.md'
      - 'LICENSE'
      - 'package.xml'
      - 'dependencies.rosintall'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - '*.md'
      - 'LICENSE'
      - 'package.xml'
      - 'dependencies.rosintall'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {name: "(noetic)", ROS_DISTRO: noetic, BUILDER: catkin_tools}
          - {name: "(humble)", ROS_DISTRO: humble}
          - {name: "(rolling)", ROS_DISTRO: rolling}
          # - {name: "(iron)", ROS_DISTRO: iron}
          - {name: "(noetic, Debug)", ROS_DISTRO: noetic, BUILDER: catkin_tools, CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
          - {name: "(humble, Debug)", ROS_DISTRO: humble, CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
          - {name: "(rolling, Debug)", ROS_DISTRO: rolling, CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
          # - {name: "(iron, Debug)", ROS_DISTRO: iron, CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug"}
    name: ${{ matrix.env.name }}
    env:
      CCACHE_DIR: /github/home/.ccache
      UPSTREAM_WORKSPACE: dependencies.rosinstall
      CTEST_OUTPUT_ON_FAILURE: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ github.sha }}
          restore-keys: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
